version: "3.9"
services:
  relax:
    image: thachung/rosetta-relax
    command: bash relaxscript.sh
    volumes:
      - drive:/home/runtime
    secrets:
      - source: inputfile
        target: /home/runtime/inputfile.pdb
      - source: script
        target: /home/runtime/relaxscript.sh

secrets:
  inputfile:
    file: ./*.pdb
  script:
    file: ./relaxscript-greedy.sh

volumes:
  drive:
